### ISSUE TITLE
Portfolio Layout Design

### ISSUE THREAD

**Issue by MasterLeiva** [MasterLeiva/Portfolio#10]
- Implemented Grid
- Implemented CSS
- Responsive Design
- Responsive Buttons
- Template Design

**Comment by MoyasiGinko** [comment]
# Requires Changes 👍
Hi @MasterLeiva 

![](https://camo.githubusercontent.com/61c9f8a8d23e3adc2f92d8cf3505460163dd77c57072701504a59a4d41a357f3/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f333151333645484a3743355a6f494d7737392f67697068792e676966)

You have done a good job so far!
You still need to work on some issues, but you are almost there! 🫡

### Highlights
- Follows GitHub flows ✅
- Great design implementation ✅
- Responsive design ✅
- Good commit messages ✅
## Required Changes ♻️
- Please consider looking into the style.css file and properties of the elements placed on the site. they should be identical to the Figma design CSS properties. 😅 (please check the comments below). 🫡
- I suggest you also check your `index.html` file to fix some highlighted issues (from the comments below). 🫡
- It is always recommended to document your repository so that you could keep track of your changes. maybe you could do that later. 😉

## Optional suggestions

- [_OPTIONAL_] You can go through your `index.html` and `styles.css` files again and organize the code to make it look cleaner, simpler to read, and more professional. ✨ You could add comments to your code to keep track of your code and identify which section play responsible for which part. 😉

Cheers and Happy coding! 🍻💻

Feel free to leave any questions or comments in the thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Comment by MoyasiGinko** [comment]
The anchor tags in the "`Get my resume`" button and the "`See project`" buttons should be given semantic values using the "`button`" role in order to make it clear that they are buttons and not just links. Please consider replacing them, as they would make your look semantic.

**Comment by MoyasiGinko** [comment]
Please, look into the header part of the main page the `class="logo"` and `class="hamburger"` elements in the header section of the main page are not aligned from the top margin. To fix this issue, the padding on the top of the header element should be adjusted so that it is equal to the height of the logo and hamburger icon. This will ensure that the logo and hamburger icon are positioned symmetrically from the top margin of the header element.

**Comment by MoyasiGinko** [comment]
I suggest you change the color `#F55800` used in the layout, text, button, etc., and replace it with the color used in the Figma design `#FF6B00`. Please check the Figma design for further reference.  With a slight change of color code is not a significant change, but it is recommended to make your design identical to the Figma design.
